### ISSUE TITLE
Error installing setup.py 

### ISSUE THREAD

**Issue by lzucker1** [dfm/python-fsps#130]
Hi! I am attempting to use the command   ```sudo SPS_HOME=$SPS_HOME python3 setup.py install``` to install python-fsps. However, I am getting the error 

```Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    from fsps import __version__  # NOQA
  File "/mnt/c/Users/Lea/Documents/HSCFA/python-fsps/fsps/__init__.py", line 44, in <module>
    raise ImportError("Your FSPS version does not have correct history.  "
ImportError: Your FSPS version does not have correct history.  Perhaps you need to pull the most up-to-date FSPS version. Please make sure that you have the following commits in your git history, preferably with the last listed commit the same as your current FSPS commit githash: 6ad10,b5250,a23e4,45f96,05584
```
I checked, and it is true that these commits are not listed in my commit log. I am not sure why this is happening. I tried git cloning it again, but that didn't help. Do you have any advise?

**Comment by dnarayanan** [comment]
Hi,

What git hash of both python fsps and fsps are you on?   A few days ago, I was able to succesfully install both pyfsps and fsps on their latest hashes:

```(base) [desika.narayanan@login4 ~]$ cd fsps
(base) [desika.narayanan@login4 fsps]$ git rev-parse HEAD
01ba3146506d3bf9c0ed6bb4a1f3ab618c796785
(base) [desika.narayanan@login4 fsps]$ cd ~/python-fsps
(base) [desika.narayanan@login4 python-fsps]$ git rev-parse HEAD
6cb57695076870345439f8207fce094672566648```

i'm wondering if one of your codes (either pyfsps or fsps or both) need to be updated

**Comment by lzucker1** [comment]
Hi, 
Yes, I do have the most recent commit in my git log for fsps. I have tried git cloning both fsps and python-fsps multiple times, but the error persists. Thank you so much for your time with this.

**Comment by bd-j** [comment]
Hi, I'm not sure what the issue is.  The master branch of cconroy20/fsps definitely has those 5 commits in it, I just checked with a fresh clone (see also [the history](https://github.com/cconroy20/fsps/commits/master).)  At the command line the following should print out the directory that you cloned fsps into and `6ad1058`
```
cd $SPS_HOME
pwd
git log --format="format:%h" | grep 6ad1058
```
I don't know how you could have the most recent commit but none of the others.  However, you could take a chance and replace https://github.com/dfm/python-fsps/blob/main/fsps/__init__.py#L41 with `accepted = [True]` before installing.

There are some pending PRs that should simplify this checking.

**Comment by bd-j** [comment]
PS I recommend installing python-fsps and its dependencies in conda or miniconda environments (https://docs.conda.io/en/latest/index.html), which should remove the need to use sudo

**Comment by lzucker1** [comment]
Hi. Thank you for the advice; I will try that.
