### ISSUE TITLE
Using sps.isochrone() with BPASS 

### ISSUE THREAD

**Issue by pzyao** [dfm/python-fsps#178]
Hi,

I am using the python fsps code to create a simple stellar population which I then want to generate a list of isochrones at different ages. Currently we are experimenting with different isochrone libraries such as MIST, BPASS, and GENEVA. When using MIST isochrones, I could easily do it with the sps.isochrones() function. But after installing python-fsps in another environment with: 
`FFLAGS=“-DMIST=0 -DBPASS=1” python -m pip install fsps --no-binary fsps` 
I successfully switched the libraries to `(b'bpss', b'bpass', b'DL07')`

Since the documentation says 

> BPASS (in this case the spectral library and SSP parameters cannot be changed),

I created the SSP with just: `sps = fsps.StellarPopulation()`
and attempted to use the sps.isochrones() function, but gets the following warnings and **errors for BPASS**:
` COMPSP WARNING: log(Tmax)>10.2 yrs - linear extrapolation beyond this point for log(Tmax)=:   10.199999999999999`
`opt/anaconda3/envs/BPASS/lib/python3.8/site-packages/fsps/fsps.py:862: UserWarning: loadtxt: Empty input file: "/Users/XXXX/fsps_BPASS/OUTPUTS/BPASS_sfh1_1.cmd"
  cmd_data = np.loadtxt(`

I know BPASS is different because they are SSP SEDs, but I am not sure how to use these to make the isochrone table analogous to using sps.isochrones() with MIST 

Thanks in advance!

**Comment by bd-j** [comment]
Hi @pzyao, it is not possible to use `fsps.StellarPopulation().isochrones()` with the BPASS models, precisely because for these models FSPS only has access to the integrated SSP spectra, not individual stars along an isochrone.  More generally the concept of a traditional isochrone is not quite appropriate for BPASS models since two stars of the same mass and age can be in different locations on the HR diagram depending on the (distribution of) binary properties.

But `isochrones()` should probably give a more informative error message when BPASS is being used.

The "COMPSP WARNING"  is due to check in FSPS that is not tailored correctly for BPASS models.  It can be safely ignored, but the check should be updated in FSPS.

**Comment by pzyao** [comment]
I see! That's unfortunate, but thank you for answering my question.

**Comment by bd-j** [comment]
No problem, sorry it wasn't a more useful answer!
