### ISSUE TITLE
No emission lines for a SSP

### ISSUE THREAD

**Issue by ke27whal** [dfm/python-fsps#181]
I am trying to model the spectrum of a young SSP, but it seems that FSPS doesn't calculate emission lines when sfh=0? 

I initialize FSPS
`t_age = 75*1e-3`
`sp = fsps.StellarPopulation(tage = t_age, imf_type = 1, zcontinuous = 1, logzsol=-0.3, add_igm_absorption = False, add_neb_emission = True, cloudy_dust = True, agb_dust = True, nebemlineinspec = True)`

If I set the SFH to be a SSP,
`sp.params['sfh'] = 0`
`wl_gal, flux_gal_rest = sp.get_spectrum(tage=t_age, peraa=False)`

I get the following output spectrum with no emission lines:
![image](https://user-images.githubusercontent.com/15821711/182914801-93def2e9-a6db-477e-872a-fb7a9d3323d6.png)

Changing the SFH to be a tau-model rectifies this issue
`sp.params['sfh'] = 4`
`sp.params['tau'] = 0.1`
`wl_gal, flux_gal_rest = sp.get_spectrum(tage=t_age, peraa=False)`
![image](https://user-images.githubusercontent.com/15821711/182915313-4ff15a3e-3601-4522-9bd6-d2a08dad309d.png)

Is this normal? I suppose I can edit a tau-SFH to mimic that of a SSP, but it would be simpler to use `sfh=0` if at all possible.

**Comment by bd-j** [comment]
Hi @ke27whal the units of tage are Gyr, so `t_age=0.075` is already 75 Myr by which time the stars producing ionization radiation have died and there is no nebular emission - indeed FSPS does not even try to add nebular emission beyond .  Try `t_age=7.5e-3`, and please update here if you don't see any lines even at that age.

Note that delay-tau-model SFH gives nebular lines for `t_age=75e-3` because in that model the SFR continues from `t=t_age` to `t=0`, and so the population includes young stars that produce ionizing emission.

**Comment by bd-j** [comment]
assuming this is resolved, but please reopen if you are still noticing problems.
