### ISSUE TITLE
computing CSP

### ISSUE THREAD

**Issue by dptriani** [dfm/python-fsps#93]
Hi,
I want to compute the SED of a CSP. I wonder how can I do that through python-fsps. I tried fsps.StellarPopulation.compute_csp() only to get:
AttributeError: type object 'StellarPopulation' has no attribute 'compute_csp'
Thanks

**Comment by bd-j** [comment]
Hi @dptriani, please see the documentation, e.g.
http://dfm.io/python-fsps/current/stellarpop_api/

you have to instantiate the `StellarPopulation` object and then ask for the SED, e.g.
```
sp = fsps.StellarPopulation(sfh=1, tau=5, compute_vega_mags=False)
mags = fsps.get_mags(tage=13.7)
```

**Comment by dptriani** [comment]
Okay I get that.
So the method in creating SSP and CSP is exactly similar?
I am trying to compute the SED of a galaxy and I am confused because when I first try using sfh=4 the stellar mass I got is less than 1 solar mass but now I've tried using tabulah sfh and I get the reasonable stellar mass for a galaxy.

**Comment by bd-j** [comment]
yes, SSP is just `sfh=0`

for `sfh=0, 1, 4, 5` the SFH and SED are normalized so that 1 solar mass has *formed*.  Some of that will be lost to stellar winds and SNe, so the surviving stellar stellar mass is less than 1.  But you can renormalize to any stellar mass you want just by multiplyin (or, for magnitudes, subtracting `2.5*log(mass)`. For `sfh=3` the normalization is set by the input tabular SFH.

**Comment by dptriani** [comment]
Alright I get it :)
Thanks!
