### ISSUE TITLE
get_mags() execution time?

### ISSUE THREAD

**Issue by nchoksi4456** [dfm/python-fsps#96]
Hi, 

I've been playing with get_mags() and had a quick question about the execution time: we expected the call to get_mags() to take a few milliseconds, but get something more like ~0.5 seconds (see below). It's not a huge issue of course, but would you mind confirming that this is a real result (and not an issue with my machine)? This is only coming up because of some >1e4 calls to get_mags() I am trying to run.

	jwst_bands = fsps.find_filter('jwst')
	f070w_band = [jwst_bands[2]]

	sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=0, zred = 0.0,
	                                sfh=0,zmet = 19, dust_type=2, dust2=0.2)
	start = time.clock()
	for i in range(0,5):
	    normed_mags = sp.get_mags(tage=.1, bands=f070w_band, redshift = 2.0) 
	end = time.clock()
	print "average time per loop = ", (end - start)/(i+1)

with output:
`0.2826744` seconds

**Comment by bd-j** [comment]
The first calls to `get_mags()` or `get_spectrum()` trigger SSP generation, which is time consuming.  The SSPs are cached so that subsequent calls should be faster unless you change any of the parameters in `StellarPopulation.params.ssp_params`.  Also, if you don't change *any* of the parameters (as in your example) then the calls will be super fast, since it uses the cached computed magnitudes or spectra  for the composite stellar population.

So, to get timings that don't include the initial SSP setup, but do include the time it takes it to re-generate CSPs, I'd do something like:
```python
# initial SSP generation
normed_mags = sp.get_mags(tage=.1, bands=f070w_band, redshift = 2.0) 
# now loop over slightly different ages
start = time.clock()
for i in range(1,5):
    normed_mags = sp.get_mags(tage=.1 + i/100., bands=f070w_band, redshift = 2.0) 
end = time.clock()
print "average time per loop = ", (end - start)/(i)
```

**Comment by nchoksi4456** [comment]
Got it -- thank you!
