### ISSUE TITLE
Clarify ages 

### ISSUE THREAD

**Issue by dptriani** [dfm/python-fsps#97]
Hi, let me open a new issue since the issue where we discuss this before is not relevant.
Okay so before it is stated that times (tage, sf_start, etc) in FSPS is the age of universe instead of lookback time. But look at the result of this, I change the start of burst across age of universe and it is shown that the oldest burst give highest intensity (?) which is odd for me. Isn't it supposed to be the lowest? It only make sense if the age is actually lookback time, hmm.

`import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import fsps
import matplotlib.gridspec as gridspec
from matplotlib.offsetbox import AnchoredText

sps = fsps.StellarPopulation(imf_type=2)
sps.params['sfh']=1
sps.params['fburst']=0.1
sps.params['tau']=0.1

#burst at 13Gyr
sps.params['sf_start']=13
wave13, spec13 = sps.get_spectrum(tage=13.7, peraa=True)
mass13=sps.stellar_mass
x13 = wave13 / 1e4
y13 = (spec13 * wave13)

#burst at 8Gyr
sps.params['sf_start']=8
wave8, spec8 = sps.get_spectrum(tage=13.7, peraa=True)
mass8=sps.stellar_mass
x8 = wave8 / 1e4
y8 = (spec8 * wave8)

#burst at 3Gyr
sps.params['sf_start']=3
wave3, spec3 = sps.get_spectrum(tage=13.7, peraa=True)
mass3=sps.stellar_mass
x3 = wave3 / 1e4
y3 = (spec3 * wave3)

#burst at 0.01Gyr
sps.params['sf_start']=0.01
wave001, spec001 = sps.get_spectrum(tage=13.7, peraa=True)
mass001=sps.stellar_mass
x001 = wave001 / 1e4
y001 = (spec001 * wave001)

fig = plt.figure()
ax1 = plt.subplot(111)
ax1.plot(x13, y13, 'k', lw= 0.5, label='burst start=13Gyr')
ax1.plot(x8, y8, 'b', lw= 0.5, label='burst start=8Gyr')
ax1.plot(x3, y3, 'r', lw= 0.5, label='burst start=3Gyr')
ax1.plot(x001, y001, 'g', lw= 0.5, label='burst start=0.01Gyr')
ax1.set_xscale('log', nonposy='clip')
ax1.set_yscale('log', nonposy='clip')
ax1.set_ylim(1e-4, 10)
ax1.set_xlim(1e-2, 150)
ax1.set_xlabel(r'$\lambda\ (\mathrm{\mu m}) $')
ax1.set_ylabel(r'log $\lambda L_{\lambda} (L_{\odot})$')

leg = ax1.legend(loc=0, numpoints=1, labelspacing=0.1)
leg.draw_frame(False)
for t in leg.get_texts():
	t.set_fontsize('medium')

plt.show()`
![screen shot 2018-03-09 at 10 32 21 am](https://user-images.githubusercontent.com/32476693/37182435-65d8184e-2385-11e8-9223-451d1ea688a2.png)

**Comment by bd-j** [comment]
Hi @dptriani,

I think the results you are getting are correct.  Consider the burst at 13Gyr (black).  If star formation started at 13 Gyr (`sf_start=13`) after the beginning of the universe, and you ask for a spectrum at 13.7 Gyr after the beginning of the universe (`tage=13.7`) then you are looking at the population only 0.7 Gyr after *star formation* started.  On the other hand, if you have `sf_start=3` and `tage=13.7` then you are looking at the burst 10.7 Gyr after star formation started, and since the SFR is declining with cosmic time for `sfh=1`, the spectrum is dominated by older stars and looks redder and fainter.  I hope this clarifies things.
